### ISSUE TITLE
Would this crate support force_push for Sender and Queue

### ISSUE THREAD

**Issue by tianbaoluo** [asynchronics/tachyonix#12]
Hello !

First thank you for your amazing work, your crates are amazing !

I am using this channel, but In some cases, I need to support the force_push feature, so that when the Receiver cannot handle it, the Sender can discard the old Value and keep the latest Value.
Can this feature be supported? 

Thank you！

**Comment by sbarral** [comment]
Thank you for the kind words :)

I just looked into this, but unfortunately this doesn't seem possible. MPMC queues can provide a `force_push` relatively easily by basically calling `pop` and then `push` from the producer (I simplify a bit but that's the gist of it). In a MPSC queue only the (single) consumer can call `pop`, so the sender has no way to make room for another item.

I am going to close the issue for now, but if you happen to have an alternative suggestion that would help you achieve your goal, please feel free to re-open (or to open another issue if the functionality is substantially different).
