### ISSUE TITLE
Standalone crate for event primitive?

### ISSUE THREAD

**Issue by tedsta** [asynchronics/tachyonix#4]
Hi there, thanks for this excellent crate! I'm using the channel and it makes my application go the fastest out of all the channels I've tried.

Would you consider creating a separate crate just for the event primitive? I am enjoying it as a more-cumbersome-but-more-efficient alternative to `event-listener`. Currently I have just copied to entire `event` module into my crate. Now I'm getting ready to publish stuff, and I also have another crate that I would like to use the `event` module in.

**Comment by sbarral** [comment]
Hi, thanks for the feedback!

I considered this initially but couldn't figure out back then a clean way to spin out the `event` module. I did not revisit this idea after the event API was simplified, so this may actually be more doable now. Please give me till the end of the week to see if I can come with a sensible plan. At the very least, one thing that would be necessary is to make sure it works for the multiple-sender case: this would make a safe API much simpler, but has never been tested.

I assume you already now about the `diatomic-waker` crate? It is faster but limited to the single-consumer case.

**Comment by tedsta** [comment]
Thanks for considering it! No rush at all.

Thanks for the pointer to `diatomic-waker`, I had seen it before but forgotten about it. It sounds like it is a better fit for one of my use-cases which is an internal mpsc queue to send freed buffers back into the pool. I'll try swapping out `event` for `diatomic-waker` there.

**Comment by sbarral** [comment]
So I went ahead and pushed the `event` module as a self-standing crate, for now under the working name [async-event](https://github.com/asynchronics/async-event) but I am open to suggestions. There is an `async-events` crate (plural) so this may cause confusion.

I only performed obvious changes and added some documentation (there is now an example of MPMC channel). It doesn't look like much needs to be added on top of that, but I want to give myself another week before I publish it on crates.io. In particular I want to add some Loom tests to make sure that concurrent notifications work properly. Perhaps also convenience methods like `notify_one()` and `notify_all()`? Anything else?

**Comment by tedsta** [comment]
Yay thank you! I'm happy to depend on it via git for now :smile: `async-event` seems pretty fitting to me.

Current interface works great for me!

**Comment by sbarral** [comment]
`async-event` was released on crates.io! 🥳🎉

Main changes since `pre1` version:
* added Loom tests to make sure notifications sent from multiple tasks/threads work properly,
* added regular tests and run them via MIRI on CI,
* demonstrated usage with a simpler example + added a more meaty example in the `examples` folder,
* improved doc, in particular regarding differences with the `event_listener` crate,
* added `notify_one` and `notify_all` methods.
